### ISSUE TITLE
Can not process: ^1^T^Spayload

### ISSUE THREAD

**Issue by rainecheck** [Deradon/WrongCthunPlanner#1]
![wcp_err](https://user-images.githubusercontent.com/33798530/93827932-6cf1e780-fcbe-11ea-9091-7e5aaa6d71c6.png)

This tends to happen when people join or leave the raid group. Might be to do with having multiple people with WCP open when it happens, uncertain.

**Comment by Deradon** [comment]
@rainecheck ty for the feedback. I'll have a look.

**Comment by Deradon** [comment]
Fixed via: https://github.com/Deradon/WrongCthunPlanner/commit/2fb12c2edc1d47541b12aa3e2458f73cdfa3ef04
